/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedSetoresRouteImport } from './routes/_authenticated/setores'
import { Route as AuthenticatedBuscarRouteImport } from './routes/_authenticated/buscar'
import { Route as AuthenticatedVagaIdRouteImport } from './routes/_authenticated/vaga.$id'
import { Route as AuthenticatedSetorIdRouteImport } from './routes/_authenticated/setor.$id'

const AuthenticatedSetoresRoute = AuthenticatedSetoresRouteImport.update({
  id: '/_authenticated/setores',
  path: '/setores',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBuscarRoute = AuthenticatedBuscarRouteImport.update({
  id: '/_authenticated/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVagaIdRoute = AuthenticatedVagaIdRouteImport.update({
  id: '/_authenticated/vaga/$id',
  path: '/vaga/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSetorIdRoute = AuthenticatedSetorIdRouteImport.update({
  id: '/_authenticated/setor/$id',
  path: '/setor/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/buscar': typeof AuthenticatedBuscarRoute
  '/setores': typeof AuthenticatedSetoresRoute
  '/setor/$id': typeof AuthenticatedSetorIdRoute
  '/vaga/$id': typeof AuthenticatedVagaIdRoute
}
export interface FileRoutesByTo {
  '/buscar': typeof AuthenticatedBuscarRoute
  '/setores': typeof AuthenticatedSetoresRoute
  '/setor/$id': typeof AuthenticatedSetorIdRoute
  '/vaga/$id': typeof AuthenticatedVagaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated/buscar': typeof AuthenticatedBuscarRoute
  '/_authenticated/setores': typeof AuthenticatedSetoresRoute
  '/_authenticated/setor/$id': typeof AuthenticatedSetorIdRoute
  '/_authenticated/vaga/$id': typeof AuthenticatedVagaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/buscar' | '/setores' | '/setor/$id' | '/vaga/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/buscar' | '/setores' | '/setor/$id' | '/vaga/$id'
  id:
    | '__root__'
    | '/_authenticated/buscar'
    | '/_authenticated/setores'
    | '/_authenticated/setor/$id'
    | '/_authenticated/vaga/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedBuscarRoute: typeof AuthenticatedBuscarRoute
  AuthenticatedSetoresRoute: typeof AuthenticatedSetoresRoute
  AuthenticatedSetorIdRoute: typeof AuthenticatedSetorIdRoute
  AuthenticatedVagaIdRoute: typeof AuthenticatedVagaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated/setores': {
      id: '/_authenticated/setores'
      path: '/setores'
      fullPath: '/setores'
      preLoaderRoute: typeof AuthenticatedSetoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/buscar': {
      id: '/_authenticated/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof AuthenticatedBuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vaga/$id': {
      id: '/_authenticated/vaga/$id'
      path: '/vaga/$id'
      fullPath: '/vaga/$id'
      preLoaderRoute: typeof AuthenticatedVagaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/setor/$id': {
      id: '/_authenticated/setor/$id'
      path: '/setor/$id'
      fullPath: '/setor/$id'
      preLoaderRoute: typeof AuthenticatedSetorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedBuscarRoute: AuthenticatedBuscarRoute,
  AuthenticatedSetoresRoute: AuthenticatedSetoresRoute,
  AuthenticatedSetorIdRoute: AuthenticatedSetorIdRoute,
  AuthenticatedVagaIdRoute: AuthenticatedVagaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
