/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetoresRouteImport } from './routes/setores'
import { Route as IndexRouteImport } from './routes/index'

const SetoresRoute = SetoresRouteImport.update({
  id: '/setores',
  path: '/setores',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/setores': typeof SetoresRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/setores': typeof SetoresRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/setores': typeof SetoresRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/setores'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/setores'
  id: '__root__' | '/' | '/setores'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SetoresRoute: typeof SetoresRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setores': {
      id: '/setores'
      path: '/setores'
      fullPath: '/setores'
      preLoaderRoute: typeof SetoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SetoresRoute: SetoresRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
